name: Build and Deploy to Staging Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies and build
        run: |
          # Install project dependencies quickly and reliably using the lock file
          pnpm install --frozen-lockfile
          # Run the script that compiles theme assets
          pnpm run build
        working-directory: ./

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          rsync -avz --exclude-from='.rsyncignore' ./ ${{ secrets.USERNAME }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.USERNAME }}/${{ vars.DOMAIN_PATH }}/wp-content/themes/${{ vars.THEME_NAME }}/

      - name: Build and deployment completed
        run: echo "✅ Build and deployment completed successfully!"
