# TODO: See https://github.com/germanfrelo/wp-theme-template/issues/144

name: Release

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # This assumes that you have created a personal access token and configured it as a GitHub action secret named `RELEASE_PLEASE_TOKEN`.
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: node
